# Generated by Django 3.1.6 on 2021-02-21 22:30

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('usergui', '0001_initial'),
        ('devgui', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Developer',
            fields=[
                ('employee_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='devgui.employee')),
                ('phone', models.CharField(max_length=25)),
                ('devices', models.TextField()),
                ('first_workday', models.DateTimeField(default=django.utils.timezone.now)),
            ],
            bases=('devgui.employee',),
        ),
        migrations.CreateModel(
            name='Release',
            fields=[
                ('software_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='devgui.software')),
                ('suffix', models.CharField(max_length=100)),
                ('release_date', models.DateTimeField(default=django.utils.timezone.now)),
                ('improvements', models.TextField()),
                ('state', models.CharField(max_length=25)),
            ],
            bases=('devgui.software',),
        ),
        migrations.AddField(
            model_name='software',
            name='scrum_master',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sm', to='devgui.employee'),
        ),
        migrations.AddField(
            model_name='contract',
            name='id_client',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='usergui.client'),
        ),
        migrations.CreateModel(
            name='Ticket',
            fields=[
                ('complaint_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='usergui.complaint')),
                ('timestamp', models.DateTimeField(default=django.utils.timezone.now)),
                ('priority', models.IntegerField()),
                ('solved', models.BooleanField(default=False)),
                ('implemented', models.BooleanField(default=False)),
                ('id_developer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='devgui.developer')),
            ],
            bases=('usergui.complaint',),
        ),
        migrations.AddField(
            model_name='software',
            name='qa',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='qa', to='devgui.developer'),
        ),
        migrations.AddField(
            model_name='contract',
            name='id_release',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='devgui.release'),
        ),
    ]
