# Generated by Django 3.1.6 on 2021-02-21 22:30

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('usergui', '0001_initial'),
        ('devgui', '0002_auto_20210221_2330'),
    ]

    operations = [
        migrations.AddField(
            model_name='complaint',
            name='id_release',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='devgui.release'),
        ),
        migrations.AddField(
            model_name='complaint',
            name='id_user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='usergui.user'),
        ),
    ]
